name: Automated PR with Approval

on:
  schedule:
    - cron: '* * * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:      # Permite execução manual

jobs:
  prepare-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate changes
        run: |
          # Comandos para gerar mudanças automáticas
          echo "Automated update $(date)" >> auto-update.txt
          
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update: $(date)"

  create-pr:
    runs-on: ubuntu-latest
    needs: prepare-changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Pull changes from previous job
        uses: actions/download-artifact@v3
        with:
          name: auto-changes
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.AM_AUTO_APROVE_TOKEN }}
          commit-message: "Automated changes"
          title: "Auto Update: $(date +'%Y-%m-%d')"
          body: "Automated changes generated by GitHub Actions"
          branch: "auto-update-$(date +%s)"
          base: develop
          labels: automated

  auto-approve:
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.AM_AUTO_APROVE_TOKEN }}
