name: Auto-PR com Aprovação

on:
  workflow_dispatch: # Disparo manual (opcional)

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      # Passos para criar o PR automaticamente...
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.AUTO_APPROVE_TOKEN }}
          branch: develop

  auto-approve:
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Approve PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.AUTO_APPROVE_TOKEN }}  # Token personalizado
