name: Auto Approve PRs

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened, synchronize ]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.AM_AUTO_APROVE_TOKEN }}
          label: "auto-approved"
