name: Previnir Merges inválidos para o Main

on:
  pull_request:
    branches:
      - main

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          echo "Branch origem: ${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^release/ ]] && [[ ! "$BRANCH_NAME" =~ ^hotfix/ ]] && [[ "$BRANCH_NAME" != "release" ]]; then
            echo "❌ Só são permitidos merges de 'release/*', 'hotfix/*' ou 'release' para 'main'."
            exit 1
          fi
