name: Prevenir Merges inválidos para o Develop
permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop

jobs:
  check_source_branch:
    name: Prevenir Merges inválidos para o Develop
    runs-on: ubuntu-latest
    steps:
      - name: Validar branch de origem
        run: |
          echo "Branch origem: $GITHUB_HEAD_REF"
          if [[ ! "$GITHUB_HEAD_REF" =~ ^feature- ]] && [[ ! "$GITHUB_HEAD_REF" =~ ^bugfix- ]] && [[ ! "$GITHUB_HEAD_REF" =~ ^release- ]]; then
            echo "❌ Só são permitidos merges de 'feature-*', 'bugfix-*' ou 'release-*' para 'develop'."
            exit 1
          fi
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}

