name: Prevenir Merges inválidos para o Main

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check_source_branch:
    name: Prevenir Merges inválidos para o Main
    runs-on: ubuntu-latest
    steps:
      - name: Validar branch de origem
        run: |
          echo "Branch origem: $GITHUB_HEAD_REF"
          if [[ ! "$GITHUB_HEAD_REF" =~ ^release- ]] && [[ ! "$GITHUB_HEAD_REF" =~ ^hotfix- ]]; then
            echo "❌ Só são permitidos merges de 'release-*' ou 'hotfix-*' para 'main'."
            exit 1
          fi
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
