name: Previnir Merges inválidos para o Release

on:
  pull_request:
    branches:
      - 'release**'

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar branch de origem
        run: |
          echo "Branch de origem: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ Só são permitidos merges de 'develop' para 'release/*'."
            exit 1
          fi
