name: Build & Publish All Projects

on:
  workflow_dispatch:

jobs:
  define-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Set version
        id: set-version
        run: echo "version=${{ vars.SAFT_COMMON_VERSION_PREFIX }}-preview.${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

  build-core:
    needs: define-version
    uses: ./.github/workflows/saft-core-ci-cd.yml
    with:
      version: ${{ needs.define-version.outputs.version }}

  build-crypto:
    needs: define-version
    uses: ./.github/workflows/saft-cryptography-ci-cd.yml
    with:
      version: ${{ needs.define-version.outputs.version }}

  build-mz:
    needs: [define-version, build-core, build-crypto]
    uses: ./.github/workflows/saft-mozambique-ci-cd.yml
    with:
      version: ${{ needs.define-version.outputs.version }}
